version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projectdb
    ports:
      - "5532:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cpm_network

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--requirepass", "mysecurepassword"]
    ports:
      - "6579:6379"
    volumes:
      - redis-data:/data
    networks:
      - cpm_network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env.test.local
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start:dev"]
    depends_on:
      - postgres
      - redis
    networks:
      - cpm_network

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
    cpm_network:
        driver: bridge
